#!/bin/bash
set -e
KC_PASS=$(cat $KC_DB_PASSWORD)
KC_LOGIN=$(cat $KC_DB_LOGIN)
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER ${KC_LOGIN} WITH PASSWORD '${KC_PASS}';
	CREATE DATABASE keycloak;
	GRANT ALL PRIVILEGES ON DATABASE keycloak TO ${KC_LOGIN};
	ALTER DATABASE keycloak OWNER TO ${KC_LOGIN};
	CREATE SCHEMA IF NOT EXISTS keycloak AUTHORIZATION ${KC_LOGIN};
EOSQL