name: microservice-chassis

include:
  - ./infrastructure/compose.yaml

secrets:
  kc_db_login:
    environment: "KC_DB_LOGIN"
  kc_db_password:
    environment: "KC_DB_PASSWORD"
  db_root_password:
    environment: "DB_ROOT_PASSWORD"

networks:
  todo-api:

services:
  todo-api:
    build:
      context: ../src/Todo
      target: release
    develop:
      watch:
        - action: rebuild
          path: ../src/Todo
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - todo-api
    healthcheck:
      test: wget -O/dev/null http://localhost:8080/todos/health || exit 1
      timeout: 3s
      start_period: 15s

  todo-proxy:
    build:
      context: ../infrastructure/envoy/
      target: envoy-admin
      args:
        ENVOY_CONFIG: ./todo-proxy.yaml
    networks:
      - todo-api
      - default
    volumes:
      - ../certs:/certs
    depends_on:
      todo-api:
        condition: service_healthy