services:
  api:
    build:
      context: ../src/Api
      target: development
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: ../src/Api
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    healthcheck:
      test: wget http://localhost:8080/health || exit 1
      timeout: 3s
      start_period: 3s
