name: microservice-chassis

secrets:
  kc_db_password:
    environment: "KC_DB_PASSWORD"
  db_root_password:
    environment: "DB_ROOT_PASSWORD"

volumes:
  pgdata:

services:
  todo-api:
    build:
      context: ../src/Todo
      target: release
    develop:
      watch:
        - action: rebuild
          path: ../src/Todo
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    healthcheck:
      test: wget -O/dev/null http://localhost:8080/todos/health || exit 1
      timeout: 3s
      start_period: 15s

  db:
    image: postgres
    restart: always
    user: postgres
    build:
      context: ../infrastructure/db/
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_password
      KC_DB_PASSWORD: /run/secrets/kc_db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ../infrastructure/db/init:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data 
    secrets:
      - db_root_password
      - kc_db_password
    ports:
      - "5432:5432"

  ingress-proxy:
    build:
      context: ../infrastructure/envoy/
    depends_on:
      todo-proxy:
        condition: service_healthy
    ports:
    - "8080:8080"
    - "8001:8001"

  todo-proxy:
    build:
      context: ../infrastructure/envoy/
      target: envoy-admin
      args:
        ENVOY_CONFIG: ./todo-proxy.yaml
    depends_on:
      todo-api:
        condition: service_healthy