name: microservice-chassis

services:
  todo-api:
    build:
      context: ../src/Todo
      target: release
    develop:
      watch:
        - action: rebuild
          path: ../src/Todo
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    healthcheck:
      test: wget -O/dev/null http://localhost:8080/todos/health || exit 1
      timeout: 3s
      start_period: 15s

  ingress-proxy:
    build:
      context: ../infrastructure/envoy/
      args:
        ENVOY_ADMIN_PORT: 8001
    depends_on:
      todo-proxy:
        condition: service_healthy
    ports:
    - "${PORT_PROXY:-8080}:8080"
    - "${PORT_STATS:-8001}:8001"

  todo-proxy:
    build:
      context: ../infrastructure/envoy/
      target: envoy-admin
      args:
        ENVOY_CONFIG: ./todo-proxy.yaml
        ENVOY_ADMIN_PORT: 8001
    depends_on:
      todo-api:
        condition: service_healthy