# API requests for the the Todo application
# Uses the REST Client syntax for execution in VS Code

@Api_HostAddress = https://api.localhost:8080

###
GET {{Api_HostAddress}}/todos/health
Accept: application/json
Authentication: authToken

###
# @prompt authToken
GET {{Api_HostAddress}}/todos/
Accept: application/json
Authorization: Bearer {{authToken}}

###
# @prompt authToken
GET {{Api_HostAddress}}/todos/1
Accept: application/json
Authorization: Bearer {{authToken}}

###
